/* BVOM Japanese language pack. Training logic must never live here. */
globalThis.BVOM_LOCALES = globalThis.BVOM_LOCALES || {};
globalThis.BVOM_LOCALES.ja = {
  meta:{code:'ja',name:'日本語',htmlLang:'ja',dateLocale:'ja-JP'},
  language:{title:'言語'},
  shell:{workout:'ワークアウト',warmup:'ウォームアップ',history:'履歴',info:'情報',settings:'設定',cancel:'キャンセル',finish:'終了',dings:'タイマー 3 · 5 · 10'},
  lifts:{Squat:'スクワット','Bench Press':'ベンチプレス','Prone Row':'ロウ','Prone Row HLM':'プローンロウ','Supine Row':'スパインロウ','Overhead Press':'プレス',Deadlift:'デッドリフト'},
  common:{ok:'OK',save:'保存',add:'追加',edit:'編集',remove:'削除',repeat:'もう一度',progressAnyway:'このまま進む',moveToRpt:'RPTへ移行',workingTopWeight:'ワーク重量／トップ重量',accessory:'補助種目'},
  setup:{unitsTitle:'使用する重量単位は？',kg:'キログラム (kg)',lb:'ポンド (lb)',startTitle:'開始方法を選んでください',guided:'ガイド付き',manual:'手動',guidedHelp:'無理なくできるスクワット重量を1つ設定すると、選択した比率を基に他の開始重量をBVOMが提案します。',manualHelp:'各リフトの開始重量を自分で入力します。比率から自動設定はしません。',balance:'筋力バランスガイド',balanceHelp:'参考値です。開始時の比率から20%以上離れた場合に知らせます。',startProgram:'プログラム開始',ratioProfile:'比率プロファイル',male:'男性',female:'女性',noIdea:'おまかせで重量を設定',comfortableSquat:'3×5で無理なくできるスクワット開始重量',suggested:'開始重量の提案です。開始前に自由に変更できます。',startingWeights:'開始重量',independent:'各リフトは独立して進みます。'},
  workout:{title:'初心者 ABA',help:'A・B・Aがおすすめです。必要に応じてAまたはBを選べます。',straight:'ストレートセット'},
  warmup:{title:'ウォームアップ',help:'目安です。必要に応じて変更・省略してください。',none:'この重量ではウォームアップ不要です。',firstRpt:'最初のRPTワークセット',workingTop:'ワーク重量／トップ重量',emptyBar:'バーのみ',belowBar:'バー重量未満',notLoadable:'選択中のプレートでは作れません',perSide:'片側'},
  history:{progress:'進捗',local:'この端末に保存されています',title:'ワークアウト履歴',none:'まだワークアウト履歴がありません。',workout:'ワークアウト',incomplete:'未完了',duration:'時間',volume:'ボリューム',sessionNote:'セッションメモ',editNote:'メモを編集',addNote:'メモを追加',share:'ワークアウトを共有'},
  settings:{units:'重量単位',guidance:'ガイド',balance:'筋力バランスガイド',advisory:'(±20%、参考値)',equipment:'器具',standardPlates:'片側の標準プレート',microplates:'片側のマイクロプレート',advanced:'リフト詳細設定',advancedHelp:'通常は閉じています。BVOMは提案しますが、決めるのはあなたです。',backup:'バックアップと復元',backupHelp:'履歴、重量、進行状況、設定を含みます。',exportBackup:'バックアップを書き出す',restoreBackup:'バックアップを復元',rerun:'開始設定をやり直す',erase:'BVOMデータをすべて削除',mode:'モード',straightSets:'ストレートセット',rpt:'RPT',weight:'ワーク重量／トップ重量',increment:'増加幅',rptLevel:'RPTレップレベル',rptDrop:'RPT減量率 %',barWeight:'このリフトのバー重量'},
  accessories:{title:'補助種目',help:'任意 · A / B / 両方 · 筋力バランスには影響しません',add:'+ 追加',upperLower:'上半身または下半身',exercise:'種目',customExercise:'カスタム種目',workout:'ワークアウト',equipment:'器具',barbell:'バーベル',dumbbell:'ダンベル',machine:'マシン',barWeight:'バー重量',barHint:'バーベルはプレート計算を表示します。',dbHint:'重量はダンベル1個あたりです。',machineHint:'マシンに表示される数字を使ってください。',progression:'進行方法',straightSets:'ストレートセット',sets:'セット',reps:'回数',topReps:'トップセット回数',topWeight:'トップ／ワーク重量',increment:'増加幅',save:'保存',addAction:'追加',cancel:'キャンセル',editTitle:'補助種目を編集',addTitle:'補助種目を追加',chooseExercise:'種目を選ぶか入力してください。',duplicate:'同じ補助種目がすでにあります。別プログラムにしたい場合は別名で追加してください。',removeConfirm:'現在のプログラムからこの補助種目を削除しますか？履歴は残ります。',perDumbbell:'ダンベル1個あたり',rpt5:'5セットRPT',rpt3:'3セットRPT',category:{upper:'上半身',lower:'下半身'},assignment:{a:'A',b:'B',both:'両方'}},
  modals:{target:'目標',reps:'回',repsCompleted:'完了した回数',workoutSaved:'ワークアウトを保存しました！',duration:'時間',volume:'ボリューム',exercises:'種目数',incompleteTitle:'ワークアウト未完了',incompleteSub:'まだコア種目のセットが残っています。',finishQuestion:'本当に終了しますか？',goBack:'戻る',finishAnyway:'このまま終了',incompleteSaved:'未完了ワークアウトを保存しました',unfinishedNeutral:'未実施の種目は失敗として数えません。',workingWeight:'ワーク重量',unitsTitle:'重量単位を変更しますか？',unitsBody:'現在のトレーニング重量、バー重量、増加幅を変換します。履歴には記録時の単位が残ります。',plateSet:'プレート設定は標準の{unit}セットに切り替わります。',change:'変更',pounds:'ポンド',kilograms:'キログラム',setupTitle:'開始設定をやり直しますか？',setupBody:'開始設定に戻ります。ワークアウト履歴は残ります。',runSetup:'設定をやり直す',eraseTitle:'BVOMデータをすべて削除しますか？',eraseBody:'この端末の履歴、重量、設定、補助種目、進行状況を完全に削除し、この端末をBVOM Cloudからサインアウトします。BVOM Cloudに保存済みのバックアップは削除されません。',eraseType:'確認のため RESET と入力してください。',eraseEverything:'すべて削除',niceWork:'ナイス！',niceRecovery:'いい立て直し！',dontStress:'気にしない。',strongFinish:'いい締めでした。次回はメインセットを取れます。',badWorkout:'調子の悪い日はあります。次回また取りましょう。',roadTitle:'ここまで来たか…！🐝',roadBody:'{lift}はBVOMのシンプルな進行で伸ばせる範囲をほぼ使い切りました。このリフトをリセットして積み直すか、中級向けプログラムについて確認できます。',resetLift:'このリフトをリセット',learnIntermediate:'中級トレーニングを見る',intermediateTitle:'中級トレーニング',intermediateBody:'Heavy / Light / Medium と4日制 Upper / Lower は今後のBVOMプログラム候補です。'},
  sharing:{copied:'ワークアウト内容をクリップボードにコピーしました。',copyPrompt:'ワークアウト概要をコピー:',failed:'ワークアウトを共有できませんでした。'},
  backup:{restoreConfirm:'バックアップを復元しますか？\n\nこの端末の現在のBVOMデータは置き換えられます。\n\nOKを押すと復元します。',invalid:'有効なBVOMバックアップではないようです。',settingsSaved:'{lift} の設定を保存しました。'},
  praise:['追加の1回！ナイス！🐝','まだ余力あったね 😏','いいぞ。💪','目標クリア。強い！','Power Beeも満足。🐝','見せつけるね 😂'],
  notes:{title:'セッションメモ',optional:'任意 · このワークアウトと一緒に保存されます',placeholder:'今日のセッションはどうだった？',none:'メモなし',save:'保存'},
  progress:{closeMiss:'{lift}: あと少し',closeBody:'惜しかったです。同じ重量をもう一度やるか、このまま進みますか？',threeStraight:'{lift}: 3回連続で未達',threeStraightBody:'もう一度この重量に挑戦するか、このリフトをRPTへ移行しますか？<br><br><b>次のRPT:</b> {preview}',repeatStraight:'ストレートを再挑戦',movedRpt:'{lift}をRPTへ移行します。',nextTarget:'次の目標: {preview}',threeRpt:'{lift}: RPTで3回連続未達',threeRptBody:'もう一度この重量に挑戦するか、次の低回数ターゲットへ進みますか？<br><br><b>次:</b> {preview}',keepProgressing:'このまま進む',movingOn:'{lift}は次へ進みます。'},
  layoff:{close:'閉じる',title:'おかえり！',week:'前回のワークアウトから1週間以上空いています。',dontJump:'前回の重量にいきなり戻さないでください。',setup:'<b>開始設定</b>でスクワット重量を約<b>10%</b>下げ、他のリフトをBVOMに再計算させる方法もあります。',longer:'もっと長く空いた場合は<b>20%以上</b>下げる必要があるかもしれません。',punch:'軽めから始めて積み直しましょう。',joke:'もちろん無視して筋肉痛になるのも自由です。😂'},
  pb:{newPb:'自己ベスト更新！',backupReminder:'バックアップのお知らせ',backupBody:'そろそろバックアップしてもいい頃です。'},
  infoHtml(ctx){
    const {unit,smallInc,dlInc,exampleWork,exampleDrop}=ctx;
    return `<div class="infoHero"><img src="./icon-192.png" alt="BVOM Power Bee"><h2>BVOM</h2><b>BEST VERSION OF MYSELF</b><div class="tagline">シンプルに進める。必要な時だけ調整する。強くなる。</div></div>
<div class="infoCard"><h3>BVOMを選ぶ理由</h3><p>BVOMは、10年以上にわたり初心者の筋力向上を手伝ってきた経験から生まれました。腰に不安のある職人、上半身と脚の筋力バランスに差のあるサーファー、年齢を重ねても強く動ける身体を保ちたい人、そしてまったくの初心者まで、さまざまな人を対象にしてきました。</p><p>多くの初心者に複雑なトレーニングは必要ありません。基本動作を学び、継続してトレーニングし、少しずつ重量を増やして身体を適応させます。これが<b>漸進性過負荷</b>です。</p><p>レジスタンストレーニングは、筋肉だけでなく腱、結合組織、骨にも段階的な刺激を与えます。軽く始める。動きを学ぶ。少し重量を足す。食べる、寝る、回復する。そして繰り返す。</p><p><b>ロケット科学ではありません。でも、ちゃんと効きます。</b></p></div>
<div class="infoCard"><h3>誰のためのプログラム？</h3><p>BVOMは主に<b>初心者向けの全身筋力プログラム</b>です。中級の筋力トレーニング、パワーリフティング、ボディビルの土台にもなります。筋力が高まれば、筋肉を増やせる可能性も広がります。</p><p>忙しく、筋トレ自体を競技にするつもりがない人なら、仕事、体調不良、旅行、その他の予定に合わせてBVOMを回していくだけで、生涯必要な筋力プログラムとして十分なこともあります。あるリフトだけがストレートセットの線形進行を本当に卒業したら、そのリフトだけを<b>RPT（リバース・ピラミッド・トレーニング）</b>へ移し、他のリフトは通常どおり進められます。さらに必要になれば、Heavy / Light / Medium のような中級プログラムへ進むこともできます。</p></div>
<div class="infoCard"><h3>RPT</h3><p>BVOMはストレートセットで伸ばせる間はその方法を続けます。本当に停滞した時は、重いトップセットと軽めのバックオフを組み合わせるRPTへ移行できます。失敗後のレスキューセットは、その日のトレーニングを有効に終えるためのものです。</p></div>
<div class="infoCard"><h3>BVOMの基本スケジュール</h3><p>BVOMは、できるだけセッション間に回復日を入れた<b>週3回の A–B–A</b>で最も使いやすくなっています。</p><div class="programBox"><b>月曜 — A</b><br>スクワット 3×5<br>ベンチプレス 3×5<br>ロウ 3×5<br><br><b>水曜 — B</b><br>スクワット 3×5<br>プレス 5×5<br>デッドリフト 1×5<br><br><b>金曜 — A</b><br>スクワット 3×5<br>ベンチプレス 3×5<br>ロウ 3×5</div><p>日曜 / 火曜 / 木曜でも同じように使えます。1週間の頻度は、スクワット3回、ベンチ2回、ロウ2回、プレス1回、デッドリフト1回です。</p><p>プレスは通常、コアリフトの中で総負荷が最も軽いため、5×5で有効なボリュームを確保します。デッドリフトは一般に最も重く疲労も大きいため、やり過ぎると回復を妨げます。特にスクワットを週3回行う場合はなおさらです。</p><p><b>BVOMは B–A–B を推奨しません。</b> 3日制プログラムではワークアウトAを意図的に土台にしています。</p><p>週2回しかできない場合は、<b>Aを週1回、Bを週1回</b>行ってください。週の総量は減りますが、5つのコアリフトすべてをトレーニングできます。</p></div>
<div class="infoCard"><h3>軽く始める</h3><p>最初から重くしすぎないでください。身体が大きな負荷を受ける前に、動作パターンを覚える時間が必要です。すべてのワークレップは、良いフォームと狙った<b>可動域</b>で行ってください。</p><p>開始重量が重すぎてフォームが崩れているなら、重量を約<b>20%</b>落とし、動きを整えてから再び積み上げます。</p></div>
<div class="infoCard"><h3>漸進性過負荷</h3><p>BVOMは基本的に同じワーク重量で規定セットを行う<b>ストレートセット</b>から始めます。良いフォームで完了できたら、次回そのリフトを進めます。</p><div class="programBox">スクワット +${smallInc} ${unit}<br>ベンチプレス +${smallInc} ${unit}<br>ロウ +${smallInc} ${unit}<br>プレス +${smallInc} ${unit}<br>デッドリフト +${dlInc} ${unit}</div><p>小さな増加でも、長期間にわたり継続すれば非常に大きな変化になります。</p></div>
<div class="infoCard"><h3>回数を落とした時</h3><p>いずれ線形進行は難しくなります。BVOMは残りの仕事を<b>リバース・ピラミッド方式</b>へ移します。重量を下げるほど、目標回数を増やします。</p><div class="programBox"><b>例 — スクワット ${exampleWork} ${unit}, 3×5</b><br>${exampleWork}×5<br>${exampleWork}×5<br>${exampleWork}×4 ❌<br><br>BVOMが追加:<br><b>${exampleDrop}×5</b></div><p>もっと早いセットで失敗した場合、BVOMはさらに重量を下げて回数目標を増やすことがあります。その日の完了できない重量を何度も無理に繰り返すのではなく、有効なトレーニング量を確保します。</p></div>
<div class="infoCard"><h3>停滞する前に確認</h3><p>まず3つ確認してください。<b>睡眠は足りている？ 食事は足りている？ セット間の休憩は十分？</b></p><p>筋力トレーニングは有酸素運動ではありません。ウォームアップには通常、決められた休憩は不要です。準備できたら進めて構いません。序盤のワークセットなら3分以下で足りることもあります。重量が重くなるにつれて自然と長い休憩が必要になります。5分でも問題ありません。次の重いセットを成功させるために<b>10分</b>必要なら、10分休んでください。</p><p>回復に問題がないのに何度も停滞する場合、BVOMが通常の失敗処理と進行方法を案内します。ストレートセットは機能する限り続け、本当に停滞したリフトは通常RPTへ移行します。手動でデロードするかどうかは、最後まであなたが決めます。</p></div>
<div class="infoCard"><h3>休み明け</h3><p>生活には色々あります。目安として、約<b>1週間</b>トレーニングが空いたならワーク重量を約<b>10%</b>下げるのも良い方法です。もっと長く空いた場合は<b>20%以上</b>下げた方がよいこともあります。その後、また少しずつ進めてください。</p><p>BVOMは「軽めから始めた方がよいかもしれない」と知らせることはありますが、<b>自動でデロードはしません</b>。重量を下げるか、どれだけ下げるかはあなたが決めます。</p></div>
<div class="infoCard"><h3>ウォームアップは準備。疲労させない</h3><p>ウォームアップはワークセットの準備です。BVOMは必要に応じて段階的に重量を上げます。ロウやデッドリフトの頃にはすでに身体が温まっているため、不要な軽いセットは省きます。</p><p><b>準備できるだけ温める。ウォームアップを本番にしない。</b></p></div>
<div class="infoCard"><h3>筋力バランスガイド</h3><p>5つのコアリフトから大きな筋力差を知らせますが、比率は<b>ルールではなく目安</b>です。体格、年齢、経験、ケガ、得意不得意で変わります。</p></div>
<div class="infoCard"><h3>補助種目</h3><p>コアリフトが土台です。補助種目は弱点補強、筋肥大、好きな動きを追加するために使えます。補助種目は独立して進み、筋力バランスガイドには影響しません。</p></div>
<div class="infoCard"><h3>リフトを学ぶ</h3><p>BVOMはトレーニングを組みます。実際のリフト方法は、質の高い指導から学んでください。以下はおすすめのテクニック解説です。</p><b>スクワット</b><a class="resourceBtn" href="https://youtu.be/QhVC_AnZYYM?is=aCm2zqWWT5BD4L00" target="_blank">スクワット技術 — Mark Rippetoe / Art of Manliness ↗</a><a class="resourceBtn" href="https://youtu.be/vmNPOjaGrVE?is=5hZKKEZerlUYil53" target="_blank">スクワット技術 — Alan Thrall ↗</a><b>ベンチプレス</b><a class="resourceBtn" href="https://youtu.be/Bmjr4Q6je8I?is=ApBPJmk7sJLDLQYO" target="_blank">ベンチプレス技術 ↗</a><b>ロウ</b><a class="resourceBtn" href="https://youtu.be/RQU8wZPbioA?is=dUoiEIA7q5S-4tv4" target="_blank">バーベルロウ — 解説1 ↗</a><a class="resourceBtn" href="https://youtu.be/6JVSjte9F-M?is=YkoUH0rQqGTMjFpH" target="_blank">バーベルロウ — Mark Rippetoe ↗</a><a class="resourceBtn" href="https://youtu.be/mdo51_CE4gs?si=HHqP6_UFyb-oQ3gX" target="_blank">代替種目：パワーラックで行うシールロウ — BVOM ↗</a><b>オーバーヘッドプレス</b><a class="resourceBtn" href="https://youtu.be/CnBmiBqp-AI?is=OhMQaFQhKynsbJnJ" target="_blank">プレス技術 — Mark Rippetoe ↗</a><b>デッドリフト</b><a class="resourceBtn" href="https://youtu.be/MBbyAqvTNkU?is=m_bJi87UI1Eni_sE" target="_blank">デッドリフト技術 — Alan Thrall ↗</a></div>
<div class="infoCard"><h3>種目は絶対ではない</h3><p>BVOMは基本のバーベル種目を勧めますが、5つのコア枠はあなた自身、使える器具、状況に合わせて変更して構いません。<b>スクワット</b>は別のスクワット種目にできます。<b>ロウ</b>はシールロウでも構いません。<b>プレス</b>は適切なマシンプレスに置き換えられます。<b>デッドリフト</b>はラックプルでも構いません。</p><p>筋力バランスの範囲はあくまでガイドです。種目を置き換えると比較自体の意味が薄れることがあります。それでも問題ありません。<b>何をトレーニングしているかを一番よく分かっているのはあなたです。</b></p></div>
<div class="infoCard"><h3>BVOMをインストール</h3><p><b>Android:</b> ChromeでBVOMを開く → ︙メニュー → <b>アプリをインストール</b> → 画面の指示に従う。</p><p><b>iPhone / iPad:</b> SafariでBVOMを開く → 共有 → <b>ホーム画面に追加</b> → <b>Web Appとして開く</b>を有効 → 追加。</p></div>
<div class="infoCard"><h3>バックアップと同期</h3><p>重量、進行状況、補助種目、履歴は<b>この端末／ブラウザ内</b>に保存されます。</p><p>設定からいつでも<b>バックアップを書き出す</b>ことができ、<b>バックアップを復元</b>で手動の復元や端末間の移行ができます。</p><p>自動バックアップや別の端末からデータを使いたい場合は、設定で<b>BVOM Cloud</b>を有効にできます。アカウントやインターネット接続がなくても、BVOMは通常どおり使用できます。</p></div>
<div class="infoCard"><h3>BVOMが考える。あなたは持ち上げる。</h3><p>動作を学ぶ。可動域を守る。軽く始める。継続する。食べる。寝る。回復する。少しずつ重量を足す。</p><p><b>自分のベストバージョンへ。</b> 🐝🏋️</p></div>
<div class="infoCard"><h3>BVOMをより良くするために</h3><p>バグ、アイデア、改善案があれば教えてください。</p><a class="feedbackBtn" href="mailto:bvomstrength@gmail.com?subject=BVOM%20Feedback">✉ フィードバックを送る</a><div class="infoNote">bvomstrength@gmail.com</div></div>
<div class="infoCard infoNote"><b>重要:</b> BVOMは一般的な筋力トレーニングのガイドであり、医療上の診断や治療ではありません。自分の能力の範囲でトレーニングしてください。ケガ、病気、その他の健康上の制限がある場合は、必要に応じて専門家へ相談してください。</div>`;
  }
};
