/* BVOM English language pack.
   Training logic must never live in language files. */
globalThis.BVOM_LOCALES = globalThis.BVOM_LOCALES || {};
globalThis.BVOM_LOCALES.en = {
  meta:{code:'en',name:'English',htmlLang:'en',dateLocale:'en-AU'},
  language:{title:'Language'},
  shell:{workout:'WORKOUT',warmup:'WARM-UP',history:'HISTORY',info:'INFO',settings:'SETTINGS',cancel:'CANCEL',finish:'FINISH',dings:'DINGS 3 · 5 · 10'},
  lifts:{Squat:'Squat','Bench Press':'Bench Press','Prone Row':'Row','Prone Row HLM':'Prone Row','Supine Row':'Supine Row','Overhead Press':'Press',Deadlift:'Deadlift'},
  common:{ok:'OK',save:'SAVE',add:'ADD',edit:'edit',remove:'remove',repeat:'REPEAT',progressAnyway:'PROGRESS ANYWAY',moveToRpt:'MOVE TO RPT',workingTopWeight:'working/top weight',accessory:'Accessory'},
  setup:{
    unitsTitle:'What units do you lift in?',kg:'KILOGRAMS (kg)',lb:'POUNDS (lb)',startTitle:'How do you want to start?',guided:'GUIDED',manual:'MANUAL',
    guidedHelp:'Set one comfortable squat weight. BVOM suggests the other starting lifts from your selected ratio profile.',
    manualHelp:'Enter each starting lift yourself. BVOM will not use ratios to set your weights.',balance:'Strength Balance Guidance',
    balanceHelp:'Advisory only. Warn if a lift moves more than 20% from the selected starting relationship.',startProgram:'START PROGRAM',ratioProfile:'Ratio profile',male:'MALE',female:'FEMALE',noIdea:'NO IDEA — JUST GIVE ME THE WEIGHTS',
    comfortableSquat:'Comfortable starting squat for 3×5',suggested:'Suggested starting weights — edit any of them before starting.',startingWeights:'Starting weights',independent:'Every lift is independent.'
  },
  workout:{title:'Beginner ABA',help:'A · B · A is suggested. Choose A or B whenever needed.',straight:'STRAIGHT'},
  warmup:{title:'Warm-up',help:'Guidance only — change or skip sets as needed.',none:'No warm-up required at this load.',firstRpt:'first RPT work set',workingTop:'working/top weight',emptyBar:'empty bar',belowBar:'below bar weight',notLoadable:'not loadable with selected plates',perSide:'per side'},
  history:{progress:'Progress',local:'Saved locally on this device',title:'Workout history',none:'No workouts saved yet.',workout:'Workout',incomplete:'INCOMPLETE',duration:'Duration',volume:'Volume',sessionNote:'Session note',editNote:'EDIT NOTE',addNote:'ADD NOTE',share:'SHARE WORKOUT'},
  settings:{
    units:'Weight units',guidance:'Guidance',balance:'Strength Balance Guidance',advisory:'(±20%, advisory only)',equipment:'Equipment',standardPlates:'Standard plates per side',microplates:'Microplates per side',advanced:'Advanced Lift Settings',advancedHelp:'Collapsed by default. BVOM guides; you decide.',
    backup:'Backup & restore',backupHelp:'Backup includes history, weights, progression and settings.',exportBackup:'EXPORT BACKUP',restoreBackup:'RESTORE BACKUP',rerun:'RUN STARTING SETUP AGAIN',erase:'ERASE ALL BVOM DATA',mode:'Mode',straightSets:'Straight sets',rpt:'RPT',weight:'Working / top weight',increment:'Progression increment',rptLevel:'RPT rep level',rptDrop:'RPT drop %',barWeight:'Bar weight for this lift'
  },
  accessories:{
    title:'Accessories',help:'Optional · A, B or Both · no effect on strength balance',add:'+ ADD',upperLower:'Upper or Lower',exercise:'Exercise',customExercise:'Custom exercise',workout:'Workout',equipment:'Equipment',barbell:'Barbell',dumbbell:'Dumbbell',machine:'Machine',barWeight:'Bar weight',barHint:'Barbell loads show plate maths.',dbHint:'Weight is per dumbbell.',machineHint:'Use the number shown on the machine.',progression:'Progression',straightSets:'Straight Sets',sets:'Sets',reps:'Reps',topReps:'Top-set reps',topWeight:'Top / working weight',increment:'Increment',save:'SAVE',addAction:'ADD',cancel:'CANCEL',editTitle:'EDIT ACCESSORY',addTitle:'ADD ACCESSORY',chooseExercise:'Choose or enter an exercise.',duplicate:'That accessory already exists. Add a different name if you want separate programming.',removeConfirm:'Remove this accessory from your current program? Its workout history will stay.',perDumbbell:'per dumbbell',rpt5:'5-set RPT',rpt3:'3-set RPT',category:{upper:'Upper',lower:'Lower'},assignment:{a:'A',b:'B',both:'Both'}
  },
  modals:{
    target:'Target',reps:'reps',repsCompleted:'Reps completed',workoutSaved:'Workout saved!',duration:'Duration',volume:'Volume',exercises:'Exercises',
    incompleteTitle:'WORKOUT NOT COMPLETE',incompleteSub:'You still have core sets remaining.',finishQuestion:'Are you sure you want to finish?',goBack:'GO BACK',finishAnyway:'FINISH ANYWAY',incompleteSaved:'Incomplete workout saved',unfinishedNeutral:'Unfinished exercises were not counted as failures.',workingWeight:'Working weight',
    unitsTitle:'CHANGE WEIGHT UNITS?',unitsBody:'Current training weights, bars and increments will be converted. History keeps the units originally recorded.',plateSet:'Plate settings will use the standard {unit} set.',change:'CHANGE',pounds:'Pounds',kilograms:'Kilograms',
    setupTitle:'RUN STARTING SETUP AGAIN?',setupBody:'This will take you back through the starting setup. Your workout history will remain saved.',runSetup:'RUN SETUP',
    eraseTitle:'ERASE ALL BVOM DATA?',eraseBody:'This permanently deletes your history, weights, settings, accessories and progression from this device, and signs this device out of BVOM Cloud. Any existing BVOM Cloud backup is not deleted.',eraseType:'Type RESET to confirm.',eraseEverything:'ERASE EVERYTHING',
    niceWork:'NICE WORK!',niceRecovery:'NICE RECOVERY!',dontStress:"DON'T STRESS.",strongFinish:'Strong finish. You’ll get the main set next time.',badWorkout:'Bad workouts happen. You’ll get it next time.',
    roadTitle:'BROOOOO… YOU ACTUALLY GOT HERE. 🐝',roadBody:'You’ve taken {lift} about as far as BVOM’s simple progression is designed to go. Reset this lift and build again, or look at the programs available for what comes next.',resetLift:'RESET THIS LIFT',learnIntermediate:'SEE PROGRAM OPTIONS',intermediateTitle:'WHAT NEXT?',intermediateBody:'HLM RPT and the 4-Day Split are available now for lifters who can no longer progress reliably from workout to workout. Bodybuilding is also available if your goal has shifted toward hypertrophy. When you’re ready, use Starting Setup to choose your next program.'
  },
  sharing:{copied:'Workout copied to clipboard.',copyPrompt:'Copy workout summary:',failed:'Could not share this workout.'},
  backup:{restoreConfirm:'RESTORE BACKUP?\n\nThis will replace BVOM data currently on this device.\n\nPress OK to replace and restore.',invalid:'That does not look like a valid BVOM backup.',settingsSaved:'{lift} settings saved.'},
  praise:['Extra rep! Nice work. 🐝','Had another one in you, huh? 😏','Now we’re talking. 💪','Target beaten. Strong work.','Power Bee approves. 🐝','Okay, show-off. 😂'],
  infoHtml(ctx){
    const {unit,smallInc,dlInc,exampleWork,exampleDrop}=ctx;
    return `<div class="infoHero"><img src="./icon-192.png" alt="BVOM Power Bee"><h2>BVOM</h2><b>BEST VERSION OF MYSELF</b><div class="tagline">Simple progression. Intelligent adjustment. Get stronger.</div></div>
<div class="infoCard"><h3>Why BVOM?</h3><p>BVOM grew out of more than a decade of experience helping novice lifters get stronger — from tradespeople with bad backs, to surfers with upper-body and leg-strength imbalances, to older lifters wanting to remain strong and capable, and complete beginners.</p><p>Most beginners don't need complicated training. Learn the basic movements, train consistently, gradually add weight and allow your body to adapt. That's <b>progressive overload</b>.</p><p>Resistance training provides a progressive stimulus to muscles, tendons, connective tissues and bones. Start light. Learn the movements. Add a little weight. Eat, sleep, recover, and repeat.</p><p><b>It's not rocket science — but it works.</b></p></div>
<div class="infoCard"><h3>Who is BVOM for?</h3><p>BVOM is primarily a <b>novice general-strength program</b>. It can build a foundation for intermediate strength training, powerlifting or bodybuilding. More strength also gives you greater potential to build muscle.</p><p>For someone with a busy life and no intention of making lifting a sport, cycling BVOM around work, sickness, holidays and other commitments may be all the strength programming they ever need. When an individual lift genuinely outgrows straight-set linear progression, BVOM can move that lift into <b>reverse pyramid training (RPT)</b> while the other lifts keep progressing normally. More advanced programming such as Heavy / Light / Medium can come later if you eventually need it.</p></div>
<div class="infoCard"><h3>Reverse pyramid training</h3><p>BVOM pushes straight-set progression for as long as it works. When a lift genuinely stalls, RPT can keep progression moving by combining a heavy top set with lighter, higher-rep back-offs. Rescue work after a failed main set remains a failed prescription: finish productively, then get it next time.</p></div>
<div class="infoCard"><h3>How to run BVOM</h3><p>BVOM works best as a <b>three-day-per-week A–B–A program</b>, with recovery between sessions where possible.</p><div class="programBox"><b>MONDAY — A</b><br>Squat 3×5<br>Bench Press 3×5<br>Row 3×5<br><br><b>WEDNESDAY — B</b><br>Squat 3×5<br>Press 5×5<br>Deadlift 1×5<br><br><b>FRIDAY — A</b><br>Squat 3×5<br>Bench Press 3×5<br>Row 3×5</div><p>Sunday / Tuesday / Thursday works just as well. Weekly frequency: Squat 3×, Bench 2×, Row 2×, Press 1× and Deadlift 1×.</p><p>The press is normally the lightest-tonnage core lift, so 5×5 provides useful volume. The deadlift is generally the heaviest lift and is highly fatiguing; overdoing it can interfere with recovery, especially alongside squatting three times per week.</p><p><b>BVOM does not recommend B–A–B.</b> Workout A is deliberately the foundation of the three-day program.</p><p>Only have two days? Use <b>A once and B once per week</b>. You'll still train all five core lifts with less weekly volume.</p></div>
<div class="infoCard"><h3>Leave your ego at the door</h3><p>Start light. Your body needs time to learn movement patterns before they become heavily loaded. Every working rep should use good technique and the intended <b>full range of motion</b>.</p><p>If technique is breaking down because you started too heavy, reduce the weight around <b>20%</b>, clean up the movement and work back up.</p></div>
<div class="infoCard"><h3>Progressive overload</h3><p>BVOM starts with <b>straight sets across</b>: the same working weight for all prescribed sets. Complete the work with good technique and BVOM progresses the lift next time.</p><div class="programBox">Squat +${smallInc} ${unit}<br>Bench +${smallInc} ${unit}<br>Row +${smallInc} ${unit}<br>Press +${smallInc} ${unit}<br>Deadlift +${dlInc} ${unit}</div><p>Small increases accumulated consistently over time can produce enormous changes.</p></div>
<div class="infoCard"><h3>When you miss a rep</h3><p>Eventually linear progression gets hard. BVOM transitions the remaining work into a <b>reverse-pyramid approach</b>: as the weight comes down, the reps go up.</p><div class="programBox"><b>Example — Squat ${exampleWork} ${unit}, 3×5</b><br>${exampleWork}×5<br>${exampleWork}×5<br>${exampleWork}×4 ❌<br><br>BVOM adds:<br><b>${exampleDrop}×5</b></div><p>If failure occurs earlier, BVOM can reduce the load again and increase the rep target, preserving productive training volume without repeatedly grinding against a weight you can't complete that day.</p></div>
<div class="infoCard"><h3>Before you deload</h3><p>Ask three questions: <b>Enough sleep? Enough food? Enough rest between sets?</b></p><p>Strength training isn't cardio. Warm-ups generally need no prescribed rest — if you're ready, go. Early working sets may need three minutes or less. As weights become heavier you'll naturally need longer. Five minutes is fine. If you need <b>10 minutes</b> to make the next heavy set, take 10 minutes.</p><p>If recovery is in order but you repeatedly stall, BVOM will guide you through its normal failure and progression options. Straight sets are pushed for as long as they work; RPT is the normal next step when a lift genuinely stalls. You remain in control of any manual deload.</p></div>
<div class="infoCard"><h3>Returning after time away</h3><p>Life happens. As a simple guide, after about <b>one week away</b>, reduce working weights around <b>10%</b>. After a longer layoff, around <b>20% or more</b> may be appropriate. Then resume gradual progression.</p><p>BVOM may remind you that starting lighter could be sensible, but it will <b>not automatically deload you</b>. You decide whether to reduce the weight and by how much.</p></div>
<div class="infoCard"><h3>Warm up — don't wear yourself out</h3><p>A warm-up prepares you for the working sets. BVOM calculates progressively heavier warm-ups and uses different patterns where appropriate. By rows or deadlifts you've already done substantial work, so unnecessary empty-bar sets aren't required.</p><p><b>Warm up enough to be ready. Don't turn the warm-up into the workout.</b></p></div>
<div class="infoCard"><h3>Strength Balance Guidance</h3><p>BVOM uses the five core lifts to flag significant strength imbalances. These ratios are <b>guidelines, not laws</b>. Body proportions, age, training history, injuries and natural strengths all influence individual lifts.</p></div>
<div class="infoCard"><h3>Accessories</h3><p>The core lifts remain the foundation. Optional accessories can target weaknesses, add muscle-building work or include movements you enjoy. They progress independently and <b>do not affect Strength Balance Guidance</b>.</p></div>
<div class="infoCard"><h3>Learn the lifts</h3><p>BVOM programs your training. Good instruction teaches you how to perform the lifts. These are recommended technique resources.</p><b>Squat</b><a class="resourceBtn" href="https://youtu.be/QhVC_AnZYYM?is=aCm2zqWWT5BD4L00" target="_blank">Squat technique — Mark Rippetoe / Art of Manliness ↗</a><a class="resourceBtn" href="https://youtu.be/vmNPOjaGrVE?is=5hZKKEZerlUYil53" target="_blank">Squat technique — Alan Thrall ↗</a><b>Bench Press</b><a class="resourceBtn" href="https://youtu.be/Bmjr4Q6je8I?is=ApBPJmk7sJLDLQYO" target="_blank">Bench technique ↗</a><b>Row</b><a class="resourceBtn" href="https://youtu.be/RQU8wZPbioA?is=dUoiEIA7q5S-4tv4" target="_blank">Barbell row — resource 1 ↗</a><a class="resourceBtn" href="https://youtu.be/6JVSjte9F-M?is=YkoUH0rQqGTMjFpH" target="_blank">Barbell row — Mark Rippetoe ↗</a><a class="resourceBtn" href="https://youtu.be/mdo51_CE4gs?si=HHqP6_UFyb-oQ3gX" target="_blank">Alternative: Seal row in a power rack — BVOM ↗</a><b>Overhead Press</b><a class="resourceBtn" href="https://youtu.be/CnBmiBqp-AI?is=OhMQaFQhKynsbJnJ" target="_blank">Press technique — Mark Rippetoe ↗</a><b>Deadlift</b><a class="resourceBtn" href="https://youtu.be/MBbyAqvTNkU?is=m_bJi87UI1Eni_sE" target="_blank">Deadlift technique — Alan Thrall ↗</a></div>
<div class="infoCard"><h3>The lifts aren't law</h3><p>BVOM recommends the basic barbell lifts, but the five core slots can be adapted to suit you, your equipment and your circumstances. <b>Squat</b> can be another squat variation. <b>Row</b> can be a seal row. <b>Press</b> may be a suitable machine press. <b>Deadlift</b> may be a rack pull.</p><p>Strength-balance ranges are guidance only. If you substitute a movement, the comparison may no longer mean much. That's okay — <b>you know what you're training.</b></p></div>
<div class="infoCard"><h3>Install BVOM</h3><p><b>Android:</b> Open BVOM in Chrome → three-dot menu → <b>Install app</b> (or Install and create shortcut) → follow the prompts.</p><p><b>iPhone / iPad:</b> Open BVOM in Safari → Share → <b>Add to Home Screen</b> → turn on <b>Open as Web App</b> → Add.</p></div>
<div class="infoCard"><h3>Backup & sync</h3><p>BVOM saves your weights, progression, accessories and history <b>locally on this device/browser</b>.</p><p>You can <b>Export Backup</b> at any time and restore or transfer your data manually with <b>Restore Backup</b> in Settings.</p><p>Your BVOM account is used for access. BVOM still saves training data <b>locally first</b>, with automatic cloud backup and cross-device restore available while signed in.</p></div>
<div class="infoCard"><h3>BVOM does the thinking. You do the lifting.</h3><p>Learn the movements. Use full range of motion. Start light. Train consistently. Eat. Sleep. Recover. Add a little weight.</p><p><b>Become your Best Version.</b> 🐝🏋️</p></div>
<div class="infoCard"><h3>Help make BVOM better</h3><p>BVOM is still evolving. Found a bug, have an idea or think something could work better?</p><a class="feedbackBtn" href="mailto:bvomstrength@gmail.com?subject=BVOM%20Feedback">✉ SEND FEEDBACK</a><div class="infoNote">bvomstrength@gmail.com</div></div>
<div class="infoCard infoNote"><b>Important:</b> BVOM provides general strength-training guidance, not medical diagnosis or treatment. Train within your capabilities. If injury, illness or another medical limitation affects your training, seek appropriate professional advice.</div>`;
  }
};
// Additional operational strings kept separate from training logic.
Object.assign(globalThis.BVOM_LOCALES.en, {
  notes:{title:'SESSION NOTES',optional:'Optional · saved with this workout',placeholder:'How did the session feel?',none:'NO NOTE',save:'SAVE'},
  progress:{closeMiss:'{lift}: close miss',closeBody:'You were close. Repeat this weight, or progress anyway?',threeStraight:'{lift}: three failed attempts',threeStraightBody:'Another crack at this weight, or move this lift to RPT?<br><br><b>Next RPT:</b> {preview}',repeatStraight:'REPEAT STRAIGHT',movedRpt:'{lift} is moving to RPT.',nextTarget:'Next target: {preview}',threeRpt:'{lift}: three failed RPT attempts',threeRptBody:'Another crack at this weight, or keep progressing with the next lower-rep target?<br><br><b>Next:</b> {preview}',keepProgressing:'KEEP PROGRESSING',movingOn:'{lift} is moving on.'},
  layoff:{close:'Close',title:'WELCOME BACK!',week:'It\'s been over a week since your last workout.',dontJump:"Don't jump straight back in where you left off.",setup:'Consider going to <b>Starting Setup</b>, lowering your squat weight by around <b>10%</b>, and let BVOM recalculate your other lifts.',longer:'Been away longer? You may need to drop <b>20% or more</b>.',punch:'Start lighter and build back up.',joke:'Or don\'t and be sore. Your body. 😂'},
  pb:{newPb:'NEW PB!',backupReminder:'Backup reminder',backupBody:'Might be time for a backup.'}
});
